### ISSUE TITLE
Feature Request - Access To Results Of Online Tests

### ISSUE THREAD

**Issue by halso** [omcandido/test_bem#1]
Hi Cándido,

Sorry - I tried to work out how to message you through GitHub, but couldn't - so contacting you by creating a Feature Request here.

I read about Daryl Bem's experiment and "Feeling The Future" paper at:

https://mitch-horowitz-nyc.medium.com/is-precognition-real-a01805e3d723

today and read the description of the experiment in his paper.  Fascinating stuff.  Then I found your code at:

https://github.com/omcandido/test_bem

and your live online test at:

https://farm.pcibex.net/r/XPIuJP/

I'm just wondering if you've collected many results from people doing the test, and whether you would consider putting the data online publicly?  If it's just a raw data file, I may be interested in creating something to turn it into a Google Sheet or visualisation or something...

Thanks

Steve.

**Comment by omcandido** [comment]
Hi Steve,

Thank you for your interest in our study!

You can find the raw data here: https://github.com/omcandido/test_bem/tree/master/analysis
There is a results.csv with the raw collected data and even the R script we used to parse it and analyse it.

Additionally, I have added our report: https://github.com/omcandido/test_bem/blob/master/Report.pdf
Check out Appendix B if all you want is a table summarising the collected data.

I hope you find these useful.

Best,
Cándido

**Comment by halso** [comment]
Hi Cándido

Thanks for that.  It was good to read the report at:-
https://github.com/omcandido/test_bem/blob/master/Report.pdf

and that you didn't find the same results.  Sorry.  I should have RTFM as I now see these were provided in the first lines of https://github.com/omcandido/test_bem/  I suppose my brain was looking for a section about data results and analysis :-)

I have a (vague) theory that meditation etc helps "expand" people's ability to sense forward and backwards in time, which correlates with Bem's experimental idea of including a relaxation idea, and also being in a distraction free environment. When people takes drugs or do meditation that sense that the "music is enveloping you" I think is related to an expanded consciousness of time.  I've experienced it myself once after doing a bit of mediation.  I wouldn't really trust remote, web based participants to do these things well/properly or even at all (especially the distraction free environment) so that may have had some effect on the negative results?

I'm equally willing to believe that Bem's experimental results were effected by things like interaction with the experimental people, selective dropping of results/participants or other factors that are hard to predict or understand.

The article I read at:

https://mitch-horowitz-nyc.medium.com/is-precognition-real-a01805e3d723

did say that some people did try replicating the experiments, and although some of them did replicate the results - the people who did the meta-analysis ignored them.  There's always two sides to every story, so maybe there was good reasons for dropping/ignoring them.

So, I'm not convinced either way, but it was great to see your open source project and read your analysis.

Thanks

Steve.

**Comment by omcandido** [comment]
Hi, 

Don't worry, I just added those lines to the readme to make it easier for users to find the data and the report.

Indeed, this experiment was done as part of an experimentation course for my master's, for which we only had a few weeks to plan, set up, collect the data and analyse the results, so we could only replicate the original one to a limited extent. I still hope someone with more resources than us can benefit from this publicly available experiment and improve on it (also, I had no luck getting the original software Bem used, although it seems to have been made public at some point).

What I think would make these kinds of studies more compelling would be using exclusively participants with a high sensitivity index. Since we can agree that a small minority of individuals report having the ability to recall the future, randomly sampling participants may dilute the effect size of those sensitive participants. It would take a single sensitive subject that can consistently display such abilities to convincingly prove the existence of psi.

Best,
Cándido
